### ISSUE TITLE
Test 08 - Make adding 1 photo and mood tracker available to free users while locking guides and meditations

### ISSUE THREAD

**Issue by IC-development** [LinusCDE/doomarkable#7]
Requirements

Limiting photo uploads for free users

Objective:
Limit free users to one photo upload, offering unlimited uploads to premium users.

Requirements:

- Implement a check on the photo upload feature to restrict free users to a single upload.
- Display a paywall prompting users to upgrade to a premium plan if they attempt to upload more than one photo.
- Ensure that premium users can upload an unlimited number of photos without restrictions.
- Update the user interface (UI) to clearly indicate the photo upload limits for free and premium users.
- Backend support for tracking the number of photo uploads per user and enforcing the upload limit for free users.

User stories:

- As a free user, I should be able to upload only one photo and be prompted to upgrade if I attempt to upload more.
- As a premium user, I should be able to upload an unlimited number of photos without any restrictions.

Making mood tracker available to all users

Objective:
Ensure the mood tracker is available to both free and premium users.

Requirements:

- Remove any existing restrictions that limit the mood tracker to premium users.
- Update the UI to make the mood tracker accessible to all users.
- Ensure that all users can access, use, and save their mood entries.

User stories:

- As a free user, I should be able to access and use the mood tracker without any restrictions.
- As a premium user, I should be able to access and use the mood tracker without any changes to my current experience.

Locking guides and meditations behind paywall

Objective:
Restrict access to guides and meditations to premium users only.

Requirements:

- Implement a paywall for guides and meditations, restricting access to free users.
- The only guide available to free users is “The Energy of Gratitude Living”. Should be the first guide in the list.
- Display a paywall prompting users to upgrade to a premium plan if they attempt to access these features.
- [Update the UI to clearly indicate that guides and meditations are premium features **(Variation #2).**](https://www.figma.com/design/0JA6kfKBu4bDDULimeBIQP/Five-Minute-Journal---Applica-UX-Design?node-id=6361-38235&t=U4xq7iicArF9rCwG-1)
- [[Remove Guides from the Home tab.](https://www.figma.com/design/0JA6kfKBu4bDDULimeBIQP/Five-Minute-Journal---Applica-UX-Design?node-id=6364-48655&t=U4xq7iicArF9rCwG-1)](https://www.figma.com/design/0JA6kfKBu4bDDULimeBIQP/Five-Minute-Journal---Applica-UX-Design?node-id=6364-48655&t=U4xq7iicArF9rCwG-1)
- Ensure that premium users can access guides and meditations without any restrictions.

User stories:

- As a free user, I should be prompted to upgrade to a premium plan if I attempt to access guides and meditations.
- As a premium user, I should have unrestricted access to guides and meditations.

**Comment by LinusCDE** [comment]
Wrong repo I guess :sweat_smile:
